name: Reusable Release (cargo)
on:
  workflow_call:
jobs:
  publish:
    name: Publish cargo crates
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Release - cargo
        uses: release-plz/action@2eb1d8bcb770b4c48ccfaad919734b38b51958c9 # v0.5.131
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
